version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - echo ENVIRONMENT - $ENVIRONMENT
      - echo STAGE - $STAGE
      - ENVIRONMENT=$ENVIRONMENT serverless deploy --stage $STAGE -v
